version: '2.3'
services:
  CHINESE_OCR:
    runtime: nvidia
    image: "chineseocr:v2"
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    volumes:
      - .:/code
    command: /bin/bash
